# Ml Data Preprocessing file

##Objective
To understand the dataset, clean and preprocess a dataset so that it can be used for ML

##Dataset
Using Diabetes dataset.

The dataset contains information such as:
- Pregnancies
- Glucose
- BloodPressure
- SkinThickness
- Insulin
- BMI
- DiabetesPedigreeFunction
- Age
- Outcome

The target variable is Outcome.

In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('D:\\AI_Pioneers_INternship\\diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
df.shape

(768, 9)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [7]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [8]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

The datset contains the  zero values in several columns some of them like pregrancies and outcome are possibly zero as a living person can have them. But columns Glucose, BloodPressure, SkinThickness, Insulin, and BMI are treated as potentially missing/invalid measurements as it's not possible for living being to have them zero

In [10]:
(df == 0).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                     500
dtype: int64

In [13]:
clean_df = df.copy()

In [14]:
cols_with_invalid_zero = [
    'Glucose',
    'BloodPressure',
    'SkinThickness',
    'Insulin',
    'BMI'
]

clean_df[cols_with_invalid_zero] = clean_df[cols_with_invalid_zero].replace(0, np.nan)

In [15]:
clean_df.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [16]:
(clean_df.isnull().sum() / len(clean_df) * 100).round(2)

Pregnancies                  0.00
Glucose                      0.65
BloodPressure                4.56
SkinThickness               29.56
Insulin                     48.70
BMI                          1.43
DiabetesPedigreeFunction     0.00
Age                          0.00
Outcome                      0.00
dtype: float64

In [17]:
clean_df[cols_with_invalid_zero].describe()

          Glucose  BloodPressure  SkinThickness     Insulin         BMI
count  763.000000     733.000000     541.000000  394.000000  757.000000
mean   121.686763      72.405184      29.153420  155.548223   32.457464
std     30.535641      12.382158      10.476982  118.775855    6.924988
min     44.000000      24.000000       7.000000   14.000000   18.200000
25%     99.000000      64.000000      22.000000   76.250000   27.500000
50%    117.000000      72.000000      29.000000  125.000000   32.300000
75%    141.000000      80.000000      36.000000  190.000000   36.600000
max    199.000000     122.000000      99.000000  846.000000   67.100000

In [18]:
clean_df['Glucose'] = clean_df['Glucose'].fillna(clean_df['Glucose'].median())

clean_df['BloodPressure'] = clean_df['BloodPressure'].fillna(clean_df['BloodPressure'].mean())

clean_df['SkinThickness'] = clean_df['SkinThickness'].fillna(clean_df['SkinThickness'].mean())

clean_df['Insulin'] = clean_df['Insulin'].fillna(clean_df['Insulin'].median())

clean_df['BMI'] = clean_df['BMI'].fillna(clean_df['BMI'].mean())

## Handling Missing Values

Zero values in Glucose, BloodPressure, SkinThickness, Insulin, and BMI were treated as missing/invalid values and replaced with NaN.

For imputation, median was used for Glucose and Insulin because their distributions showed right-skewness. Mean was used for BloodPressure, SkinThickness, and BMI because their mean and median were relatively close and there was no strong evidence of skewness from the initial statistics.

Pregnancies and Outcome were not modified because zero is a valid value for these columns.

In [19]:
clean_df.duplicated().sum()

np.int64(0)

In [20]:
clean_df[clean_df.duplicated()]

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []

## Checking for Duplicate Rows

I checked the dataset for completely duplicated rows using `duplicated()`.

The dataset contains 0 duplicate rows, so no rows were removed at this stage.